version: "3.9"

services:
  mysql:
    image: mysql:9.0
    command: --lower_case_table_names=1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gandaya
      - MYSQL_USER=prisma # not used
      - MYSQL_PASSWORD=prisma
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P3306']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - ./docker/mysql:/var/lib/mysql

volumes:
  mysql-data: